/**
 * Clear Test Data Script for Omerald Diagnostic Center
 * 
 * Clears all test data generated by generate-data.ts
 * 
 * Usage:
 *   npx tsx clear-data.ts
 * 
 * Environment Variables:
 *   MONGO_URI or MONGODB_URI - MongoDB connection string
 */

import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../../omeraldDiagnostic-v3/.env.local') });
dotenv.config({ path: path.join(__dirname, '../../omeraldDiagnostic-v3/.env') });
dotenv.config({ path: path.join(__dirname, '.env') });

const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || '';
if (!mongoURI) {
  console.error('❌ Error: MONGO_URI or MONGODB_URI environment variable is not set');
  process.exit(1);
}

const clearData = async () => {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(mongoURI);
    
    while (mongoose.connection.readyState !== 1) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    await mongoose.connection.db.admin().ping();
    console.log('✅ Connected to MongoDB\n');

    const db = mongoose.connection.db;

    console.log('🧹 Clearing test data...\n');

    // Delete users with test phone numbers
    const userResult = await db.collection('users').deleteMany({
      phoneNumber: { $regex: /^\+1555555(010[1-9]|01[1-9][0-9]|0150)$/ }
    });
    console.log(`✅ Deleted ${userResult.deletedCount} users`);

    // Delete all profiles (DCs)
    const profileResult = await db.collection('profiles').deleteMany({});
    console.log(`✅ Deleted ${profileResult.deletedCount} diagnostic centers`);

    // Delete all branches
    const branchResult = await db.collection('branches').deleteMany({});
    console.log(`✅ Deleted ${branchResult.deletedCount} branches`);

    // Delete all tests
    const testResult = await db.collection('tests').deleteMany({});
    console.log(`✅ Deleted ${testResult.deletedCount} tests`);

    // Delete all reports
    const reportResult = await db.collection('reports').deleteMany({});
    console.log(`✅ Deleted ${reportResult.deletedCount} reports\n`);

    const totalDeleted = userResult.deletedCount + profileResult.deletedCount + 
                         branchResult.deletedCount + testResult.deletedCount + reportResult.deletedCount;
    
    console.log(`✅ Cleanup complete! Total documents deleted: ${totalDeleted}\n`);

  } catch (error) {
    console.error('❌ Error during data cleanup:', error);
    throw error;
  } finally {
    await mongoose.disconnect();
    console.log('🔌 Disconnected from MongoDB');
  }
};

// Run the script
clearData()
  .then(() => {
    console.log('\n✅ Script completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Script failed:', error);
    console.error(error.stack);
    process.exit(1);
  });



