/**
 * Clear User App Test Data
 * 
 * Clears all test data generated by generate-data.ts
 * 
 * Usage:
 *   npx tsx clear-data.ts
 */

import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../../omerald-app-v3F/.env.local') });
dotenv.config({ path: path.join(__dirname, '../../omerald-app-v3F/.env') });
dotenv.config({ path: path.join(__dirname, '.env') });

const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || '';
if (!mongoURI) {
  console.error('❌ Error: MONGO_URI or MONGODB_URI environment variable is not set');
  process.exit(1);
}

const clearData = async () => {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(mongoURI);
    
    while (mongoose.connection.readyState !== 1) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    await mongoose.connection.db.admin().ping();
    console.log('✅ Connected to MongoDB\n');

    const db = mongoose.connection.db;

    console.log('🧹 Clearing test data...\n');

    // Delete profiles (users and members) with phone numbers +15555550101 to +15555550170
    // (101-120 for users, 121-170 for members - 50 members for 10 users * 5 members)
    const profilesResult = await db.collection('profiles').deleteMany({
      phoneNumber: { $regex: /^\+1555555(010[1-9]|01[1-9][0-9]|01[2-6][0-9]|0170)$/ }
    });
    console.log(`✅ Deleted ${profilesResult.deletedCount} profiles`);

    // Delete user reports (reports with userId in the phone number range)
    const reportsResult = await db.collection('reports').deleteMany({
      userId: { $regex: /^\+1555555(010[1-9]|01[1-9][0-9]|01[2-6][0-9]|0170)$/ }
    });
    console.log(`✅ Deleted ${reportsResult.deletedCount} user reports`);

    // Note: We don't delete DC reports, only remove sharedReportDetails entries for our test phone numbers
    // This is because DC reports belong to the DC app and should remain
    console.log('\n⚠️  Note: DC reports are not deleted (they belong to the DC app)');
    console.log('   You may need to manually update DC reports to remove sharedReportDetails entries');

    const totalDeleted = profilesResult.deletedCount + reportsResult.deletedCount;
    console.log(`\n✅ Cleanup complete! Total documents deleted: ${totalDeleted}`);

  } catch (error) {
    console.error('❌ Error during cleanup:', error);
    throw error;
  } finally {
    await mongoose.disconnect();
    console.log('\n🔌 Disconnected from MongoDB');
  }
};

// Run the script
clearData()
  .then(() => {
    console.log('\n✅ Script completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Script failed:', error);
    console.error(error.stack);
    process.exit(1);
  });

