/**
 * Clear User App Test Data
 * 
 * Clears all test data generated by generate-data.ts
 * 
 * Usage:
 *   npx tsx clear-data.ts
 */

import mongoose from 'mongoose';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables
dotenv.config({ path: path.join(__dirname, '../../omerald-app-v3F/.env.local') });
dotenv.config({ path: path.join(__dirname, '../../omerald-app-v3F/.env') });
dotenv.config({ path: path.join(__dirname, '.env') });

const mongoURI = process.env.MONGO_URI || process.env.MONGODB_URI || '';
if (!mongoURI) {
  console.error('❌ Error: MONGO_URI or MONGODB_URI environment variable is not set');
  process.exit(1);
}

const clearData = async () => {
  try {
    console.log('🔌 Connecting to MongoDB...');
    await mongoose.connect(mongoURI);
    
    while (mongoose.connection.readyState !== 1) {
      await new Promise(resolve => setTimeout(resolve, 100));
    }
    
    await mongoose.connection.db.admin().ping();
    console.log('✅ Connected to MongoDB\n');

    const db = mongoose.connection.db;

    console.log('🧹 Clearing test data...\n');

    // Delete profiles (users and members) with phone numbers +15555550101 to +15555550170
    // Phone format: +1555555XXXX where XXXX is 0101-0170 (users: 0101-0120, members: 0121-0170)
    const phoneRegex = /^\+1555555(010[1-9]|01[1-9][0-9]|0120|01[2-6][0-9]|0170)$/;
    
    // First, find all matching profiles to see what we're deleting
    const matchingProfiles = await db.collection('profiles').find({
      phoneNumber: phoneRegex
    }).toArray();
    console.log(`   Found ${matchingProfiles.length} profiles matching phone number range`);
    
    const profilesResult = await db.collection('profiles').deleteMany({
      phoneNumber: phoneRegex
    });
    console.log(`✅ Deleted ${profilesResult.deletedCount} profiles`);

    // Delete user reports (reports with userId in the phone number range)
    const matchingReports = await db.collection('reports').find({
      userId: phoneRegex
    }).toArray();
    console.log(`   Found ${matchingReports.length} reports matching phone number range`);
    
    const reportsResult = await db.collection('reports').deleteMany({
      userId: phoneRegex
    });
    console.log(`✅ Deleted ${reportsResult.deletedCount} user reports`);
    
    // Also delete by email pattern (in case phone numbers don't match or were changed)
    // This helps if there are profiles with these emails but different phone numbers
    const emailDeleteResult = await db.collection('profiles').deleteMany({
      email: { $regex: /@example\.com$/ }
    });
    if (emailDeleteResult.deletedCount > 0) {
      console.log(`✅ Deleted ${emailDeleteResult.deletedCount} profiles by email pattern (@example.com)`);
    }
    
    // Also delete reports that might have been created by these profiles
    // (Some reports might not have userId matching phone pattern)
    const emailReportsResult = await db.collection('reports').deleteMany({
      $or: [
        { userId: { $regex: /^\+1555555/ } }, // Any phone starting with +1555555
        { userName: { $exists: true } } // Any report with userName (most user reports have this)
      ]
    });
    if (emailReportsResult.deletedCount > 0) {
      console.log(`✅ Deleted ${emailReportsResult.deletedCount} additional reports`);
    }

    // Note: We don't delete DC reports, only remove sharedReportDetails entries for our test phone numbers
    // This is because DC reports belong to the DC app and should remain
    console.log('\n⚠️  Note: DC reports are not deleted (they belong to the DC app)');
    console.log('   You may need to manually update DC reports to remove sharedReportDetails entries');

    const totalDeleted = profilesResult.deletedCount + reportsResult.deletedCount;
    console.log(`\n✅ Cleanup complete! Total documents deleted: ${totalDeleted}`);

  } catch (error) {
    console.error('❌ Error during cleanup:', error);
    throw error;
  } finally {
    await mongoose.disconnect();
    console.log('\n🔌 Disconnected from MongoDB');
  }
};

// Run the script
clearData()
  .then(() => {
    console.log('\n✅ Script completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('\n❌ Script failed:', error);
    console.error(error.stack);
    process.exit(1);
  });

